# Generated by Django 5.1.4 on 2025-07-22 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_orderitem_product_price_alter_orderitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='razorpay_order_id',
            new_name='paynow_poll_url',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='razorpay_payment_id',
            new_name='paynow_reference',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='razorpay_payment_signature',
        ),
    ]
