# Generated by Django 5.1.4 on 2025-07-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_rename_razorpay_order_id_cart_paynow_poll_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='redirect_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
