# Generated by Django 5.1.4 on 2025-07-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_cart_hash_cart_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
