# Generated by Django 5.1.4 on 2025-07-22 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_cart_is_delivered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='paynow_reference',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='is_delivered',
        ),
    ]
