# Generated by Django 5.1.4 on 2025-11-08 17:30

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_billboards_headerbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAIApikeyBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key_name', models.CharField(max_length=100)),
                ('api_key', encrypted_model_fields.fields.EncryptedCharField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
