# Generated by Django 5.1.4 on 2025-11-08 17:51

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_openaiapikeybucket'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('api_key_name', models.CharField(max_length=100)),
                ('api_key', encrypted_model_fields.fields.EncryptedCharField()),
                ('instructions', models.TextField(blank=True, default='Generate a persuasive, customer-facing product review in a marketing tone. Focus on emotional appeal, key features, benefits, and trust-building elements. Highlight why customers should choose this product over competitors. Keep it short, natural, and engaging.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='OpenAIApikeyBucket',
        ),
    ]
