# Generated by Django 5.1.4 on 2025-11-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_openaiconfiguration_delete_openaiapikeybucket'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaiconfiguration',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
