# Generated by Django 5.1.4 on 2025-11-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_openaiconfiguration_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openaiconfiguration',
            name='instructions',
            field=models.TextField(blank=True, default='Write a persuasive, customer-facing product description in a marketing tone. Focus on the product’s key features, benefits, and unique selling points. Make it engaging, concise, and appealing to potential customers. Avoid generic phrases and emphasize why someone should buy this product.'),
        ),
    ]
