# Generated by Django 5.1.4 on 2025-11-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_openaiconfiguration_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openaiconfiguration',
            name='model',
            field=models.CharField(default='gpt-4-turbo', max_length=100),
        ),
    ]
