# Generated by Django 5.1.4 on 2025-11-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_openaiconfiguration_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openaiconfiguration',
            name='model',
            field=models.CharField(default='gpt-5', max_length=100),
        ),
    ]
