# Generated by Django 5.1.4 on 2025-07-16 13:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_productreview_dislikes_productreview_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('brand_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='brands')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_brand', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
