# Generated by Django 5.1.4 on 2025-07-16 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_productbrand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbrand',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_brands', to='products.productbrand'),
        ),
    ]
