# Generated by Django 5.1.4 on 2025-07-21 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='color_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishlist_items_by_color', to='products.colorvariant'),
        ),
    ]
