# Generated by Django 5.1.4 on 2025-11-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_wishlist_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_desription',
            field=models.TextField(blank=True),
        ),
    ]
