# Generated by Django 5.1.4 on 2025-11-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_product_product_desription'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='youtube_iframe',
            field=models.TextField(blank=True),
        ),
    ]
