# Generated by Django 5.1.4 on 2025-11-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_product_youtube_iframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='youtube_iframe',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
