# Generated by Django 5.1.4 on 2025-11-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_product_youtube_iframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='youtube_iframe',
            field=models.TextField(blank=True),
        ),
    ]
