# Generated by Django 5.1.4 on 2025-11-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_product_youtube_iframe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_desription',
            new_name='product_description',
        ),
    ]
